### PR TITLE
Update moria.

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by dvc94ch** [comment]
@philipc any comments here? :)

**Comment by philipc** [comment]
I think this crate is in need of a maintainer. (cc @luser since you did all the early work and you are listed as the author)

**Comment by dvc94ch** [comment]
Well, I don't think the changes are too controversial. This crate is more or less finished, all it would need is publishing when a new version of object gets released.

**Comment by dvc94ch** [comment]
So there isn't any time pressure, it'll be a few weeks before I make a release, however eventually I'll have to fork the repo

**Comment by philipc** [comment]
Since no-one else seems interested in this (cc @luser @fitzgen), I'd be fine with giving you write access to this repo if you want it.

**Comment by dvc94ch** [comment]
That would be ok with me. Can you also add me as an owner of the crate so that I can publish releases?

**Comment by philipc** [comment]
As far as I know, it has never been published, and someone else is squatting the name now.

**Comment by dvc94ch** [comment]
ah I thought you had reserved the name. looks like someone else did for something completely unrelated. looks like we'll have to rename it, maybe `locate-dwarf`. so if you want to give me access, I can publish it tonight.

**Comment by luser** [comment]
> I think this crate is in need of a maintainer. (cc @luser since you did all the early work and you are listed as the author)

I am definitely not actively maintaining it, although I still think it's a good idea and would love to see it become useful again. I've used it in a few tools of mine with great success. It might be worth checking with the Sentry folks as to whether it could become part of their fleet of crates in this area, or at least interop nicely with things like `symbolic`?

**Comment by dvc94ch** [comment]
Well it takes an `Object` to extract the build_id or uuid. The functions to compute the path for the debug info from those are public too. What kind of interop did you have in mind?

**Comment by dvc94ch** [comment]
@philipc I added you as an owner of the crate `locate-dwarf`, it's always good to have a backup.

Could you please rename the repo to `locate-dwarf`?

Thanks

**Comment by luser** [comment]
> Well it takes an `Object` to extract the build_id or uuid. The functions to compute the path for the debug info from those are public too. What kind of interop did you have in mind?

I guess I don't have anything specific in mind. It'd just be good to do some testing using this crate with other related crates that might want to consume debug info to ensure that the API plays nicely. I'll leave that in your hands!

**Pull request merged**
