### PR TITLE
Adds ability to find PDB for PE file

### LINKED ISSUE #44: Support for PE -> PDB lookup
I realize this crate is called "locate-dwarf" but I'd love to add support for finding a PDB based on a PE. Is that something you'd be open to?

### PR DESCRIPTION
**Pull request by schultetwin1**
Closes #44

### CODE REVIEW

**Review by dvc94ch — COMMENTED** [review]
LGTM although not familiar with pdb. can you link some spec for review?

**Comment by schultetwin1** [comment]
> LGTM although not familiar with pdb. can you link some spec for review?

For sure! Unfortunately there is no official spec for a PDB from Microsoft, but LLVM has put together a pretty detailed spec here: https://llvm.org/docs/PDB/index.html

I think what you are looking for in particular is the search order used to find a PDB? The best documentation I can find for that is here: https://docs.microsoft.com/en-us/windows/win32/debug/symbol-paths

Summarizing from that link, it looks like the PDB should be searched for in the following order:
1. Path embedded into binary
2. Search Paths

"Search Paths" are defined in the following order:
1. Paths in the `_NT_SYMBOL_PATH` environmental variable (separated by semicolons).
2. Paths in the `_NT_ALT_SYMBOL_PATH` environmental variable (separated by semicolons).
3. The directory that contains the binary

When searching in the "Search Paths" the following locations are searched in order:
1. The original path
2. A folder under the original path named with the extension of the binary
3. A folder under the original path named symbols\extension.

The "Search Paths" could also start with `cache*` and `srv*`.

For this change I think I will try to support everything except `cache*` and `srv*`.

Here is an example based on what I understand.

Let's say we have a binary named `C:\dev\myybinary.exe`. It has the following PDB path embedded in in `C:\sym\mybinary.pdb`. The environmental variable `_NT_SYMBOL_PATH` is `C:\symbols` and the environmental variable `_NT_ALT_SYMBOL_PATH` is empty. I believe we should look at the following locations in order.

1. `C:\sym\mybinary.pdb`
2. `C:\symbols\mybinary.pdb`
3. `C:\symbols\exe\mybinary.pdb`
4. `C:\symbols\symbols\exe\mybinary.pdb`
5. `C:\dev\mybinary.pdb`
6. `C:\dev\exe\mybinary.pdb`
7. `C:\dev\symbols\exe\mybinary.pdb`

**Comment by schultetwin1** [comment]
So, I will make the changes to support the `_NT_SYMBOL_PATH` and `_NT_ALT_SYMBOL_PATH` environmental variables. I will also make the changes to support the extra search paths (under the file extension and symbols/extension)

**Comment by dvc94ch** [comment]
maybe move the pdb stuff into it's own file? other than that looks good to me, sorry I forgot about this

**Review by dvc94ch — APPROVED** [review]
thanks!

**Comment by schultetwin1** [comment]
> maybe move the pdb stuff into it's own file? other than that looks good to me, sorry I forgot about this

No worries! I can do that.

**Pull request merged**
